### ISSUE TITLE
Ability to set FailureThreshold on healthchecks

### ISSUE THREAD

**Issue by jonnangle** [octodns/octodns-route53#28]
It would be nice to be able to set [FailureThreshold](https://docs.aws.amazon.com/Route53/latest/APIReference/API_HealthCheckConfig.html#Route53-Type-HealthCheckConfig-FailureThreshold) when creating healthchecks.

**Comment by ross** [comment]
Should be possible to add something to the Route53 specific healthcheck config, https://github.com/octodns/octodns-route53#health-check-options. An existing example is https://github.com/octodns/octodns-route53/blob/3aeca8d7e2225d553ceefbf4af0f0ecb510209d5/octodns_route53/__init__.py#L1113-L1116

That gets used in a couple places https://github.com/octodns/octodns-route53/blob/3aeca8d7e2225d553ceefbf4af0f0ecb510209d5/octodns_route53/__init__.py#L1185 and https://github.com/octodns/octodns-route53/blob/3aeca8d7e2225d553ceefbf4af0f0ecb510209d5/octodns_route53/__init__.py#L1366

**Comment by jonnangle** [comment]
hey @ross thanks for getting back to me! I have a PR ready to go, will push it today 👍
