### ISSUE TITLE
Latency Routing Policy

### ISSUE THREAD

**Issue by shakusbakus** [octodns/octodns-route53#35]
Working with a company that use OctoDNS to manage their Route53 DNS, we are wanting to implement latency based routing.

Is this supported? Cant see any mention of it in the documentation.

Have you got a full list of supported features including the correct syntaxes to use in the configuration files?

**Comment by ross** [comment]
> That said it does have provider specific functionality where someone has wanted/needed it and added in a clean way to configure it (without causing problems for other providers.)

To elaborate, PRs welcome. It's not really something that I have a use/case for or that would be generally applicable so I'm unlikely to get to it on my own, but I'm open to discussing developing it on contract if that's of interest.

**Comment by shakusbakus** [comment]
Thanks for the update Ross
