### ISSUE TITLE
Feature Request: Add DS record support to octodns-route53

### ISSUE THREAD

**Issue by rasturic** [octodns/octodns-route53#82]
Hi Ross & Team.

Lack of DS record support is the only thing blocking me from migrating a few of our zones from a custom script over to octodns.   All of our other zones are working well with octodns/route53 and we enjoy using it.  I'd rather use octodns over my custom script.

With respect to supporting DNSEC-enabled subdomains, DS record values are essentially text records.

Is there a particular reason support was omitted or just a matter of finding someone to do it?

Thanks!

**Comment by yzguy** [comment]
Finding someone to do it.

OctoDNS itself has support for DS records https://github.com/octodns/octodns/pull/968

**Comment by rasturic** [comment]
Excellent, thank you.  1/2 way there. 😄

**Comment by rasturic** [comment]
Merged
