### ISSUE TITLE
Add IRSA support

### ISSUE THREAD

**Issue by igor-nikiforov** [octodns/octodns-route53#91]
For now `access_key_id` and `secret_access_key` **are mandatory** when configuring `octodns_route53.Route53Provider`. But we want to avoid using bare AWS credentials and use IAM role for service account to interact with Route53 since OctoDNS deployed in our EKS cluster - https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

As I see provider using boto3 so it should be possible out of the box because when IRSA used all important environment variables are injected in container:

```
        - name: AWS_STS_REGIONAL_ENDPOINTS
          value: regional
        - name: AWS_DEFAULT_REGION
          value: us-east-1
        - name: AWS_REGION
          value: us-east-1
        - name: AWS_ROLE_ARN
          value: >-
            arn:aws:iam::xxx:role/xxx
        - name: AWS_WEB_IDENTITY_TOKEN_FILE
          value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
```

**Comment by ross** [comment]
There is some exsiting support for IAM, https://github.com/octodns/octodns-route53/blob/d9b046b2de2a8db6809efd914a624035af577a00/octodns_route53/auth.py#L17-L18. Haven't messed with IRSA so no clue what if anything needs to change to support it, but `_AuthMixin` is where that support would currently live.

I don't have a setup to test IRSA with and it's fairly $$$ to mess around with such things so I'm not likely to do so for this. PRs. welcome. 

If there's any requests required specifically as part of the auth process then the new secrets provider API may be of use. The main advantage to that route is being able to assume the role once and have multiple providers/sources use the reuslts. I'd like to explore converting the existing assume role stuff over to that at some point, but no clue when I'll get to the point of exploring it.
