### ISSUE TITLE
Trailing dots in config but not in dns provider (route53)?

### ISSUE THREAD

**Issue by jmreicha** [octodns/octodns-route53#96]
Looking at https://github.com/octodns/octodns/pull/1147 how does this work if e.g. route53 does not contain the trailing dots but the corresponding source config has them?

I ran into a case where records were changed manually without a trailing dot but the config has them and route53 tries to revert the changes every time. It looks like I have the opposite issue?

**Comment by ross** [comment]
Moved to octodns-route53 since it's likely something going on specific to it. 

octoDNS always uses trailing dots in config as that's the technically correct/cononical way to specify a FQDN. Without it searching for something like `does.not.exist.com` would result in queirying for that value, as well as things like `does.not.exist.com.yourdomain.com.` based on whatever is in your resolve.conf (or similar) search config, see https://superuser.com/questions/570082/in-etc-resolv-conf-what-exactly-does-the-search-configuration-option-do. 

Some DNS providers work with trailing `.`s and some don't, others still will silently add or remove it. It's up to each provider to deal with the translation between octoDNS's standard and the specific provider's. This is an example of the main purpose of octoDNS, providing a consistent interface to wildly varying DNS providers. 

> Looking at [octodns/octodns#1147](https://github.com/octodns/octodns/pull/1147) how does this work if e.g. route53 does not contain the trailing dots but the corresponding source config has them?

I'm not 100% clear on what the question is here, assuming the above didn't answer it. If the source of data has `.` and the target doesn't the provider for that target should deal with removing them before sending the data and remove them when pulling data out of the provider.

**Comment by jmreicha** [comment]
This one basically describes what’s going on https://github.com/octodns/octodns-route53/issues/84. That said, all of what I am trying to do are workarounds for fixing the root of the problem, so I think I just need to bite the bullet here. Unfortunately at this point in time route53 it requires records to be deleted and recreated.

**Comment by ross** [comment]
Not sure I follow. If there are targeted records in Route53 w/o trailing `.`, e.g. a `CNAME` -> `foo.bar.com` and locally in a config file `foo.bar.com.` I would expect the provider to do an update (`UPSERT`):

```console
********************************************************************************
* exxampled.com.
********************************************************************************
* route53 (Route53Provider)
*   Update
*     <CnameRecord CNAME 300, foo.exxampled.com., exxampled.com> ->
*     <CnameRecord CNAME 3600, foo.exxampled.com., exxampled.com.> (config)
*   Summary: Creates=0, Updates=1, Deletes=0, Existing Records=2
********************************************************************************
```

I manually created the record in the console w/o a `.` and then configured it locally with one. 

That should update the records in place and bring them into best practices. Not sure how that would result in a delete and create so if that's what you're seeing something else is up and we'll need an actually issue with details on the situation and steps to reproduce if it's going to be debugged.

**Comment by jmreicha** [comment]
Yep I agree, that's the behavior I was expecting to see as well but it never actually upserts. I will check a few more things in my side to make sure I'm not missing something silly and get some more details together early next week if you'd like to debug.

I appreciate the help.

**Comment by ross** [comment]
Got an email notification about a comment earlier that doesn't appear here:

<img width="1269" height="202" alt="Image" src="https://github.com/user-attachments/assets/30bbdc12-ebfb-4234-8034-aa275b778e58" />

@brianeclow do you have any repro steps or anything like that. When I looked into this long ago I couldn't reproduce the issue trying to create things either through the UI or API without the dot.

**Comment by brianeclow** [comment]
@ross:

I deleted the comment because I realized the thread was closed.

How I ran into it:
1. Existing zone in Route53
2. Dump zone, clean for compliance with trailing dot
3. Plan, shows addition of trailing dot
4. Apply, shows Route53 applies change
5. Re-plan, shows addition of trailing dot because apply was ignored by provider

Confirmation in the AWS Route53 Console:
1. Find CNAME entry without trailing dot
2. Edit entry, adding trailing dot
3. Save
4. Viewing entry shows AWS Route53 ignores the change

After looking into this, I remember I hit it before. Pre-existing CNAME entries created without the trailing dot will not get updated. Period. It is a bug with Route53. To correct this, you would need to delete the entry and recreated, potentially causing disruption. I see this case on CNAME and MX, but I am assuming it effects anything with a CNAME-like value.

I implemented a less than ideal solution, set `lenient: True` on the zone in question. However, this only solves for the current inconsistent zone data, and it will allow this inconsistency to continue unchecked with future updates on this zone.

I would like a zone processor to handle omitted trailing dot entries on Route53 to be ignored to allow the zone data within octoDNS to be `lenient: False`, this will allow easier migration to other providers in the future.

**Comment by ross** [comment]
I'll see if I can reproduce

**Comment by ross** [comment]
## UI created hosted zone with a single cname record to it whose target does not have a trailing `.`

<img width="2302" height="1006" alt="Image" src="https://github.com/user-attachments/assets/fadd5c19-7e11-4091-adae-ee20189e929d" />

## octoDNS config file

```yaml
(env) ross@trout:~/octodns/octodns-route53 $ cat config/dev.yaml 
---
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./config

  route53:
    class: octodns_route53.Route53Provider
    access_key_id: env/AWS_ACCESS_KEY_ID
    secret_access_key: env/AWS_SECRET_ACCESS_KEY

zones:
  '*':
    sources:
      - config
    targets:
      - route53
```

## dump command

```console
(env) ross@trout:~/octodns/octodns-route53 $ PYTHONPATH=. octodns-dump --config-file=config/dev.yaml --output-dir=./config exxampled.com. route53
...
  File "/home/ross/octodns/octodns-route53/env/lib64/python3.14/site-packages/octodns/record/base.py", line 84, in new
    raise ValidationError(fqdn, reasons, context)
octodns.record.exception.ValidationError: Invalid record "cname.exxampled.com."
  - CNAME value "exxampled.com" missing trailing .
```

## with --lenient

```console
(env) ross@trout:~/octodns/octodns-route53 $ PYTHONPATH=. octodns-dump --config-file=config/dev.yaml --output-dir=./config exxampled.com. route53 --lenient
...
2026-05-06T10:29:58  [139764964215680] INFO    YamlProvider[dump] plan: desired=exxampled.com.
2026-05-06T10:29:58  [139764964215680] INFO    YamlProvider[dump] populate:   found 0 records, exists=False
2026-05-06T10:29:58  [139764964215680] INFO    YamlProvider[dump] plan:   Creates=2, Updates=0, Deletes=0, Existing=0, Meta=False
2026-05-06T10:29:58  [139764964215680] INFO    YamlProvider[dump] apply: making 2 changes to exxampled.com.
```

## exxampled.com.yaml (after manually adding the trailing dot)

```yaml
---
? ''
: ttl: 172800
  type: NS
  values:
  - ns-1198.awsdns-21.org.
  - ns-2044.awsdns-63.co.uk.
  - ns-241.awsdns-30.com.
  - ns-650.awsdns-17.net.
cname:
  ttl: 300
  type: CNAME
  value: exxampled.com.
```

## sync --doit

```console
(env) ross@trout:~/octodns/octodns-route53 $ PYTHONPATH=. octodns-sync --config-file=config/dev.yaml
... 
2026-05-06T10:32:05  [139623606336384] INFO    YamlProvider[config] populate:   found 2 records, exists=True
2026-05-06T10:32:05  [139623606336384] INFO    Route53Provider[route53] plan: desired=exxampled.com.
2026-05-06T10:32:05  [139623606336384] WARNING Record Invalid record "cname.exxampled.com."
  - CNAME value "exxampled.com" missing trailing .
2026-05-06T10:32:05  [139623606336384] INFO    Route53Provider[route53] populate:   found 2 records, exists=True
2026-05-06T10:32:05  [139623606336384] INFO    Route53Provider[route53] plan:   Creates=0, Updates=1, Deletes=0, Existing=2, Meta=False
2026-05-06T10:32:05  [139623606336384] INFO    Plan 
********************************************************************************
* exxampled.com.
********************************************************************************
* route53 (Route53Provider)
*   Update
*     <CnameRecord CNAME 300, cname.exxampled.com., exxampled.com> ->
*     <CnameRecord CNAME 300, cname.exxampled.com., exxampled.com.> (config)
*   Summary: Creates=0, Updates=1, Deletes=0, Existing=2, Meta=False
********************************************************************************


2026-05-06T10:32:51  [139895735106432] INFO    Route53Provider[route53] apply: making 1 changes to exxampled.com.
2026-05-06T10:32:51  [139895735106432] INFO    Route53Provider[route53] _apply: zone=exxampled.com., len(changes)=1
2026-05-06T10:32:51  [139895735106432] INFO    Route53Provider[route53] _apply:   sending change request for batch of 1 mods, 1 ResourceRecords
2026-05-06T10:32:51  [139895735106432] INFO    Manager sync:   1 total changes
```

## Subsequent sync (reproduced issue)

```console
(env) ross@trout:~/octodns/octodns-route53 $ PYTHONPATH=. octodns-sync --config-file=config/dev.yaml
...
2026-05-06T10:33:15  [140122210667392] INFO    YamlProvider[config] populate:   found 2 records, exists=True
2026-05-06T10:33:15  [140122210667392] INFO    Route53Provider[route53] plan: desired=exxampled.com.
2026-05-06T10:33:16  [140122210667392] WARNING Record Invalid record "cname.exxampled.com."
  - CNAME value "exxampled.com" missing trailing .
2026-05-06T10:33:16  [140122210667392] INFO    Route53Provider[route53] populate:   found 2 records, exists=True
2026-05-06T10:33:16  [140122210667392] INFO    Route53Provider[route53] plan:   Creates=0, Updates=1, Deletes=0, Existing=2, Meta=False
2026-05-06T10:33:16  [140122210667392] INFO    Plan 
********************************************************************************
* exxampled.com.
********************************************************************************
* route53 (Route53Provider)
*   Update
*     <CnameRecord CNAME 300, cname.exxampled.com., exxampled.com> ->
*     <CnameRecord CNAME 300, cname.exxampled.com., exxampled.com.> (config)
*   Summary: Creates=0, Updates=1, Deletes=0, Existing=2, Meta=False
********************************************************************************
```

## changset being sent

Same command with debug, picked out and reformatted the changeset xml

```xml
 <Changes>                               
   <Change>                              
     <Action>UPSERT</Action>             
     <ResourceRecordSet>                 
       <Name>cname.exxampled.com.</Name> 
       <ResourceRecords>                 
         <ResourceRecord>                
           <Value>exxampled.com.</Value> 
         </ResourceRecord>               
       </ResourceRecords>                
       <TTL>300</TTL>                    
       <Type>CNAME</Type>                
     </ResourceRecordSet>                
   </Change>                             
 </Changes>                              
```

## Summary/TL;DR

octoDNS is sending up the correct Changes, but Route53's API is ignoring the change when it just adds a trailing `.`

I'm not sure where that leaves us. The only option I can think of would be to do a delete and recreate if Route53 is just going to ignore us 😦 

I may have had things backwards in https://github.com/octodns/octodns-route53/issues/96#issuecomment-2335250771 when @jmreicha mentioned delete and create, maybe that's what they meant https://github.com/octodns/octodns-route53/issues/96#issuecomment-2335164609.

**Comment by ross** [comment]
Went ahead and tried adding it in the UI as well and it ignores it there too.

**Comment by ross** [comment]
## Unsuccessful Workaround

So bad news, code that turns the trailing . only change into a delete and create (in one batch) ends up as a noop in the Route53 API as well so there is no work-around available to octodns-route53.

```xml
<Changes>                              
  <Change>                             
    <Action>DELETE</Action>            
    <ResourceRecordSet>                
      <Name>cname.exxampled.com.</Name>
      <ResourceRecords>                
        <ResourceRecord>               
          <Value>exxampled.com</Value> 
        </ResourceRecord>              
      </ResourceRecords>               
      <TTL>300</TTL>                   
      <Type>CNAME</Type>               
    </ResourceRecordSet>               
  </Change>                            
  <Change>                             
    <Action>CREATE</Action>            
    <ResourceRecordSet>                
      <Name>cname.exxampled.com.</Name>
      <ResourceRecords>                
        <ResourceRecord>               
          <Value>exxampled.com.</Value>
        </ResourceRecord>              
      </ResourceRecords>               
      <TTL>300</TTL>                   
      <Type>CNAME</Type>               
    </ResourceRecordSet>               
  </Change>                            
</Changes>                             
```

## Manually resolving

The only solution I've found is to manually delete the record out of Route53 and have octoDNS recreate it. It then has the trailing `.`.

The other option is to mark the records as `lenient` (or in the ~near future disable the trailing-dot validations https://github.com/octodns/octodns/pull/1380)

Unfortunately going to close this one back out without a resolution. The delete/create split code is over in https://github.com/octodns/octodns-route53/pull/135
